project_id = "ngtckhrzlxgfuprgfjyp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[experimental.functions]]
name = "vapi-webhook"
verify_jwt = false

[[experimental.functions]]
name = "fetch-vapi-calls"
verify_jwt = false

[[experimental.functions]]
name = "vapi-data-sync"
verify_jwt = false

[[experimental.functions]]
name = "fetch-assistant-calls"
verify_jwt = false

[[experimental.functions]]
name = "generate-twilio-token"
verify_jwt = false