project_id = "ngtckhrzlxgfuprgfjyp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
name = "vapi-webhook"
verify_jwt = false

[[functions]]
name = "fetch-vapi-calls"
verify_jwt = false