// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngtckhrzlxgfuprgfjyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ndGNraHJ6bHhnZnVwcmdmanlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4OTIxMjYsImV4cCI6MjA1MTQ2ODEyNn0.Pw_gDNqU0e9_YWmNpXng7DSblTyBROyB_N-JdGiRFG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);